//
//  UserPoolsUIHelper.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
//

#import "UserPoolsUIHelper.h"

@implementation UserPoolsUIHelper

+ (void) setUpFormShadowForView:(UIView *)view {
    view.layer.shadowColor = [UIColor blackColor].CGColor;
    view.layer.shadowOffset = CGSizeZero;
    view.layer.shadowOpacity = 0.5;
    view.layer.shadowRadius = 5;
    view.layer.cornerRadius = 10.0;
    view.layer.borderColor = [UIColor grayColor].CGColor;
    view.layer.borderWidth = 0.5;
    view.layer.masksToBounds = NO;
}

@end
