//
//  SignInViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
//
#import <UIKit/UIKit.h>

@interface SignInViewController : UIViewController

@property (atomic) BOOL canCancel;

// Support code for Facebook provider UI.
@property (weak, nonatomic) IBOutlet UIButton *facebookButton;
// Support code for Twitter provider UI.
//@property (weak, nonatomic) IBOutlet UIButton *twitterButton;
// Support code for Google provider UI.
@property (weak, nonatomic) IBOutlet UIButton *googleButton;
// Support code for Amazon provider UI.
//@property (weak, nonatomic) IBOutlet UIButton *amazonButton;
// Support code for custom sign-in provider UI.
@property (weak, nonatomic) IBOutlet UIButton *signInButton;
@property (weak, nonatomic) IBOutlet UIButton *signUpButton;
@property (weak, nonatomic) IBOutlet UIButton *forgotPasswordButton;
@property (weak, nonatomic) IBOutlet UILabel *orSignInWithLabel;
@property (weak, nonatomic) IBOutlet UIImageView *logoView;
@property (weak, nonatomic) IBOutlet UIView *tableFormView;
@property (weak, nonatomic) IBOutlet UITableView *tableView;
@property (weak, nonatomic) IBOutlet NSLayoutConstraint *logoViewHeight;

@property (nonatomic, copy) void (^didCompleteSignIn)(BOOL success);

@end
