//
//  MainViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.20
//
#import <Foundation/Foundation.h>
#import "MainViewController.h"
#import "DemoFeature.h"
#import <AWSMobileHubHelper/AWSMobileHubHelper.h>
#import "SignInViewController.h"

static NSString * LOG_TAG = @"MainViewController";

@interface MainViewController ()

@property (nonatomic, strong) NSMutableArray *demoFeatures;

@property (nonatomic, strong) id didSignInObserver;
@property (nonatomic, strong) id didSignOutObserver;

@end

@implementation MainViewController

#pragma mark - View Controller lifecycle

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self setupRightBarButtonItem];
    
    self.navigationItem.backBarButtonItem =
        [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                         style:UIBarButtonItemStylePlain
                                        target:nil
                                        action:nil];

    // Default theme settings.
    [self.navigationController.navigationBar
        setBackgroundColor:[UIColor colorWithRed:1.0f
                                           green:1.0f
                                            blue:1.0f
                                           alpha:1.0]];
    [self.navigationController.navigationBar
        setBarTintColor:[UIColor colorWithRed:0xF5/255.0f
                                        green:0x85/255.0f
                                         blue:0x35/255.0f
                                        alpha:1.0]];
    [self.navigationController.navigationBar
        setTintColor:[UIColor whiteColor]];


    NSLog(@"%@: Loading...", LOG_TAG);
    self.demoFeatures = [[NSMutableArray alloc] init];

    DemoFeature *demoFeature =
        [[DemoFeature alloc] initWithName:NSLocalizedString(@"User Sign-in",
                                                            @"Label for demo menu option.")
                                   detail:NSLocalizedString(@"Enable user login with popular 3rd party providers.",
                                                            @"Description for demo menu option.")
                                     icon:@"UserIdentityIcon"
                               storyboard:@"UserIdentity"];
    [self.demoFeatures addObject:demoFeature];
    
    
    
    
}


- (void)setupRightBarButtonItem {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        UIBarButtonItem *loginButton = [[UIBarButtonItem alloc] initWithTitle:nil
                                                                        style:UIBarButtonItemStyleDone
                                                                       target:self
                                                                       action:nil];
        self.navigationItem.rightBarButtonItem = loginButton;
    });

    if ([[AWSSignInManager sharedInstance] isLoggedIn]) {
        self.navigationItem.rightBarButtonItem.title = NSLocalizedString(@"Sign-Out", @"Label for the logout button.");
        self.navigationItem.rightBarButtonItem.action = @selector(handleLogout);
    }

    if (![[AWSSignInManager sharedInstance] isLoggedIn]) {
        self.navigationItem.rightBarButtonItem.title = NSLocalizedString(@"Sign-In", @"Label for the login button.");
        self.navigationItem.rightBarButtonItem.action = @selector(goToLogin);
    }
}

#pragma mark - UITableViewController delegates

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"MainViewCell"];
    
    DemoFeature *demoFeature = self.demoFeatures[indexPath.row];
    cell.imageView.image = [UIImage imageNamed:[demoFeature icon]];
    cell.textLabel.text = [demoFeature displayName];
    cell.detailTextLabel.text = [demoFeature detailText];

    return cell;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [self.demoFeatures count];
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];

    DemoFeature *demoFeature = [self.demoFeatures objectAtIndex:indexPath.row];
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:demoFeature.storyboard
                                                         bundle:nil];
    UIViewController *viewController = [storyboard instantiateViewControllerWithIdentifier:demoFeature.storyboard];
    
    [self.navigationController pushViewController:viewController
                                         animated:YES];
}

#pragma mark -


- (void)goToLogin {
    NSLog(@"%@: Handling optional sign-in", LOG_TAG);
    UIStoryboard *loginStoryboard = [UIStoryboard storyboardWithName:@"SignIn"
                                                              bundle:nil];
    SignInViewController *loginController = (SignInViewController *)[loginStoryboard instantiateViewControllerWithIdentifier:@"SignIn"];
    loginController.canCancel = YES;
    loginController.didCompleteSignIn = ^(BOOL success) {
        if (success) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [self setupRightBarButtonItem];
            });
        } else {
            // handle cancel operation
        }
    };
    UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:loginController];
    [self.navigationController presentViewController:navController
                                            animated:YES
                                          completion:nil];
         
}

- (void)handleLogout {
    if ([[AWSSignInManager sharedInstance] isLoggedIn]) {
        [[AWSSignInManager sharedInstance] logoutWithCompletionHandler:^(id result, AWSIdentityManagerAuthState authState, NSError *error) {
            [self.navigationController popToRootViewControllerAnimated:NO];
            [self setupRightBarButtonItem];
        }];
        //NSLog(@"%@: %@ Logout Successful", LOG_TAG, [signInProvider getDisplayName]);
    } else {
        assert(false);
    }
}

@end

@implementation FeatureDescriptionViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    self.navigationItem.backBarButtonItem =
        [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                         style:UIBarButtonItemStylePlain
                                        target:nil
                                        action:nil];
}

@end
